Deprecations for Stacks 2.0
blockstack/blockstack-browser pull request #2069
Opened 2021-01-10 03:28 UTC by hstove

This PR closes #2005.

Given that we will not have a working registrar at launch, I've also removed the ability to register a username from within the app.

- Removed any 'Add username' stuff when logged in
- Skip the 'username' step when signing up
- Removed the QR code on the receive page
- Removed the "Receive" button on wallet page
- Add deprecation banner
- Add deprecation notice on wallet page

![image](https://user-images.githubusercontent.com/1109058/104113698-d9feac80-52b0-11eb-9c13-01bb09fc8a72.png)

2021-01-10 03:31 UTC, hstove commented
The end-to-end tests will surely break, given that I've removed the username step from onboarding. Unless someone has a major objection, I am not going to fix those, as I don't think it's worth the time.

2021-01-10 03:43 UTC, hstove commented
Preview URL is https://deploy-preview-2069--reporter-beaver-73821.netlify.app/

2021-01-10 08:30 UTC, markmhx requested changes

2021-01-10 08:30 UTC, markmhx commented on app/js/wallet/WalletApp.js
>            <strong>NOTE:</strong> You cannot use this wallet to send and receive Stacks (STX) tokens. Also, you cannot use the Bitcoin (BTC) address on this page to fund STX transactions. This wallet
Let's link "the Stacks Wallet" here to https://blockstack.org/wallet and remove the phrase that says "See the Stacks Wallet software documentation for more information" entirely.

2021-01-10 08:30 UTC, markmhx commented on app/public/index.html
> +    Deprecated: Please switch to the Stacks Wallet or upgrade your app to Stacks.js
Let's link "Stacks Wallet" here to blockstack.org/wallet

2021-01-10 17:56 UTC, hstove commented on app/public/index.html
> +    Deprecated: Please switch to the Stacks Wallet or upgrade your app to Stacks.js
The whole banner already links to that?

2021-01-13 11:40 UTC, markmhx commented on app/public/index.html
> +    Deprecated: Please switch to the Stacks Wallet or upgrade your app to Stacks.js
Ah true

2021-01-13 17:57 UTC, timstackblock approved these changes

2021-01-13 19:27 UTC, aulneau approved these changes

2021-01-13 23:38 UTC, merged